AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  Janitor

Parameters:
  AmiMaxDays:
    Description: days to keep amis
    Default: 30
    Type: Number

  SnapsshotMaxDays:
    Description: days to keep amis
    Default: 50
    Type: Number

Globals:
  Function:
    Runtime: python3.7
Resources:
  DeregisterAmi:
    Description: Lambda deregisters old amis
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: janitor-deregister-amis
      CodeUri: ./src/deregister_ami/
      Handler: deregister_ami.lambda_handler
      Timeout: 120
      MemorySize: 128
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - "ec2:DeregisterImage"
              - "ec2:DescribeImages"
              - "ec2:DescribeRegions"
            Resource: "*"
          - Effect: Allow
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource: "arn:aws:logs:*:*:*"
      Environment:
        Variables:
          ami_max_days: !Ref AmiMaxDays

  DeleteOldSnapshots:
    Description: Lambda deletes old ebs snapshots
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: janitor-delete-snapshot
      CodeUri: ./src/delete_ebs_snapshots/
      Handler: delete_ebs_snapshots.lambda_handler
      Timeout: 120
      MemorySize: 128
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - "ec2:DescribeSnapshots"
              - "ec2:DeleteSnapshot"
            Resource: "*"
          - Effect: Allow
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource: "arn:aws:logs:*:*:*"
      Environment:
        Variables:
          snapshot_max_days: !Ref SnapsshotMaxDays
  DeleteEBSVolumes:
    Description: Lambda deletes ebs in available state
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: janitor-delete-ebs-volume
      CodeUri: ./src/delete_unattached_volumes/
      Handler: delete_volumes.lambda_handler
      Timeout: 120
      MemorySize: 128
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - "ec2:DeleteVolume"
              - "ec2:DescribeVolumes"
            Resource: "*"
          - Effect: Allow
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource: "arn:aws:logs:*:*:*"
